Fix non-replacement of binary in Travis
```
23.04s$ scripts/run.sh
  Installing cargo-fuzz v0.4.0 (file:///home/travis/build/rust-fuzz/cargo-fuzz)
error: binary `cargo-fuzz` already exists in destination as part of `cargo-fuzz v0.3.1 (file:///home/travis/build/rust-fuzz/cargo-fuzz)`
Add --force to overwrite
```